### ISSUE TITLE
Error @ 'juicer pre' with 'Command exit status: 56'

### ISSUE THREAD

**Issue by j-a-thia** [WarrenLab/hic-scaffolding-nf#7]
Hi there. :)

Ran into this issue with the pipeline. Is it a Java issue?

```
### JUICER ERROR

# ERROR ~ Error executing process > 'JUICER_PRE (1)'

# Caused by:
  # Process `JUICER_PRE (1)` terminated with an error exit status (56)

# Command executed:

  # juicer pre -a -o out_JBAT         yahs.out.bin         yahs.out_scaffolds_final.agp         contigs.fa.fai

  # asm_size=$(awk '{s+=$2} END{print s}' contigs.fa.fai)
  # java -Xmx36G -jar /data/gpfs/projects/punim1321/hic_scaff_stuff/juicer_tools.2.20.00.jar         pre out_JBAT.txt out_JBAT.hic <(echo "assembly ${asm_size}")

# Command exit status:
  # 56

# Command output:
  # WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  # WARN [2024-01-10T20:59:47,703]  [Globals.java:138] [main]  Development mode is enabled
  # Using 1 CPU thread(s) for primary task
  # Using 10 CPU thread(s) for secondary task
  # Not including fragment map
  # Start preprocess
  # Writing header
  # Writing body
  # ..
  # Writing footer
  # nBytesV5: 269722
  # masterIndexPosition: 139186245

  # Finished preprocess

  # Calculating norms for zoom BP_2500000

# Command error:
  # [I::main_pre] make juicer pre input from BIN file yahs.out.bin
  # [I::make_juicer_pre_file_from_bin] 184378474 read pairs processed
  # [I::main_pre] genome size: 48901993
  # [I::main_pre] scale factor: 1
  # [I::main_pre] chromosome sizes for juicer_tools pre -
  # PRE_C_SIZE: assembly 48901993
  # [I::main_pre] JUICER_PRE CMD: java -Xmx36G -jar ${juicer_tools} pre out_JBAT.txt out_JBAT.hic <(echo "assembly 48901993")
  # [I::main_pre] Version: 1.1
  # [I::main_pre] CMD: juicer pre -a -o out_JBAT yahs.out.bin yahs.out_scaffolds_final.agp contigs.fa.fai
  # [I::main_pre] Real time: 37.097 sec; CPU: 36.973 sec; Peak RSS: 0.001 GB
  # WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  # WARN [2024-01-10T20:59:47,703]  [Globals.java:138] [main]  Development mode is enabled
  # Using 1 CPU thread(s) for primary task
  # Using 10 CPU thread(s) for secondary task
# executor >  local (7)
# [c8/9dcd46] process > PRINT_VERSIONS     [100%] 1 of 1 ✔
# [55/43bdbf] process > SAMTOOLS_FAIDX (1) [100%] 1 of 1 ✔
# [14/285880] process > CHROMAP_INDEX (1)  [100%] 1 of 1 ✔
# [1a/6e38a3] process > CHROMAP_ALIGN (1)  [100%] 1 of 1 ✔
# [db/2c190b] process > YAHS_SCAFFOLD (1)  [100%] 1 of 1 ✔
# [de/8696cf] process > JUICER_PRE (1)     [100%] 1 of 1, failed: 1 ✘
# [10/2d1250] process > ASSEMBLY_STATS (1) [100%] 1 of 1 ✔
# ERROR ~ Error executing process > 'JUICER_PRE (1)'

# Caused by:
  # Process `JUICER_PRE (1)` terminated with an error exit status (56)

# Command executed:

  # juicer pre -a -o out_JBAT         yahs.out.bin         yahs.out_scaffolds_final.agp         contigs.fa.fai

  # asm_size=$(awk '{s+=$2} END{print s}' contigs.fa.fai)
  # java -Xmx36G -jar /data/gpfs/projects/punim1321/hic_scaff_stuff/juicer_tools.2.20.00.jar         pre out_JBAT.txt out_JBAT.hic <(echo "assembly ${asm_size}")

# Command exit status:
  # 56

# Command output:
  # WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  # WARN [2024-01-10T20:59:47,703]  [Globals.java:138] [main]  Development mode is enabled
  # Using 1 CPU thread(s) for primary task
  # Using 10 CPU thread(s) for secondary task
  # Not including fragment map
  # Start preprocess
  # Writing header
  # Writing body
  # ..
  # Writing footer
  # nBytesV5: 269722
  # masterIndexPosition: 139186245

  # Finished preprocess

  # Calculating norms for zoom BP_2500000

# Command error:
  # [I::main_pre] make juicer pre input from BIN file yahs.out.bin
  # [I::make_juicer_pre_file_from_bin] 184378474 read pairs processed
  # [I::main_pre] genome size: 48901993
  # [I::main_pre] scale factor: 1
  # [I::main_pre] chromosome sizes for juicer_tools pre -
  # PRE_C_SIZE: assembly 48901993
  # [I::main_pre] JUICER_PRE CMD: java -Xmx36G -jar ${juicer_tools} pre out_JBAT.txt out_JBAT.hic <(echo "assembly 48901993")
  # [I::main_pre] Version: 1.1
  # [I::main_pre] CMD: juicer pre -a -o out_JBAT yahs.out.bin yahs.out_scaffolds_final.agp contigs.fa.fai
  # [I::main_pre] Real time: 37.097 sec; CPU: 36.973 sec; Peak RSS: 0.001 GB
  # WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  # WARN [2024-01-10T20:59:47,703]  [Globals.java:138] [main]  Development mode is enabled
  # Using 1 CPU thread(s) for primary task
  # Using 10 CPU thread(s) for secondary task
  # Not including fragment map
  # Start preprocess
  # Writing header
  # Writing body
  # ..
  # Writing footer
  # nBytesV5: 269722
  # masterIndexPosition: 139186245

  # Finished preprocess

  # Calculating norms for zoom BP_2500000java.lang.NullPointerException: Cannot invoke "java.util.Iterator.hasNext()" because "this.currentIterator" is null
        # at juicebox.data.iterator.ListOfListIterator.hasNext(ListOfListIterator.java:44)
        # at juicebox.data.iterator.IteratorContainer.getNumberOfContactRecords(IteratorContainer.java:54)
        # at juicebox.data.iterator.ListOfListIteratorContainer.getIsThereEnoughMemoryForNormCalculation(ListOfListIteratorContainer.java:56)
        # at juicebox.tools.utils.norm.NormalizationCalculations.<init>(NormalizationCalculations.java:59)
        # at juicebox.tools.utils.norm.GenomeWideNormalizationVectorUpdater.getWGVectors(GenomeWideNormalizationVectorUpdater.java:167)
        # at juicebox.tools.utils.norm.GenomeWideNormalizationVectorUpdater.updateHicFileForGWfromPreAddNormOnly(GenomeWideNormalizationVectorUpdater.java:132)
        # at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:159)
        # at juicebox.tools.clt.old.AddNorm.launch(AddNorm.java:83)
        # at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:185)
        # at juicebox.tools.HiCTools.main(HiCTools.java:97)

# Work dir:
  # /tmp/work/de/8696cf44088ce591d902c247aac5e0

# Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 # -- Check '.nextflow.log' file for details
```

I took a closer look at the files in the **work/** directory and it seems to have output the assembly:

```
>ls -1 work/36/d925755d2c140d69df201cee727c02
contigs.fa.fai
out_JBAT.assembly
out_JBAT.assembly.agp
out_JBAT.hic
out_JBAT.liftover.agp
out_JBAT.txt
yahs.out.bin
yahs.out_scaffolds_final.agp
```

And these files all have data in them... so it seems fine. Any ideas?

Thanks heaps.

~ JT

**Comment by esrice** [comment]
Hi JT,

Well, it looks like everything else in the pipeline worked, so have you taken a look at the output scaffolds to see whether scaffolding was successful? All the other steps succeeded, so there should be output in your output directory. The step that's failing is just for making a heatmap of the scaffolds you can open with Juicebox. Usually when I see this error it's because the scaffolding in the previous step didn't work due to, e.g., no usable Hi-C read pairs, but the scaffolding step doesn't throw an error when this happens, it just doesn't make any joins. So take a look at the pipeline output; my guess is that the real problem is happening long before the juicer pre step, but the other steps are just doing nothing instead of crashing.

Hope this helps!
Ed
